### ISSUE TITLE
Feature Request: Windows Support

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_perl#30]
This is the tracking issue for what's described in the README:
https://github.com/bazelbuild/rules_perl/blob/2f4f36f454375e678e81e5ca465d4d497c5c02da/README.md#L43-L45

This way folks can subscribe to something in case this functionality gets added.

**Comment by UebelAndre** [comment]
Closed by #32 

Thanks!

**Comment by jheaff1** [comment]
@UebelAndre  it’s worth saying that this repo provides a perl toolchain but it currently doesn’t work with `perl_` rules

**Comment by UebelAndre** [comment]
Ah, good point. I'll re-open 😅

**Comment by jesseschalken** [comment]
> @UebelAndre it’s worth saying that this repo provides a Windows perl toolchain but it currently doesn’t work with `perl_` rules.

What is missing to allow the Strawberry Perl toolchain to work with this ruleset?

**Comment by jheaff1** [comment]
I’m not quite sure, I’m afraid. I simply tried to run the tests within this repo on Windows and they failed. There is probably a reliance on bash, so MSYS2 would be required on Windows, which isn’t ideal.

**Comment by UebelAndre** [comment]
@skeletonkey is this implemented?

**Comment by UebelAndre** [comment]
@skeletonkey this functionality is still desired and does not appear to be implemented. Can this issue be reopened?

**Comment by UebelAndre** [comment]
This change would actually be implemented by https://github.com/bazel-contrib/rules_perl/pull/84
