### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/rules_perl#34]

**Comment by UebelAndre** [comment]
This would mean a lot to see done. ❤️

**Comment by skeletonkey** [comment]
I don't believe that I have the proper privileges to do this.  @PiotrSikora is this something that you have access to do?

**Comment by PiotrSikora** [comment]
I don't. @philwo could you make the change or find someone who can?

**Comment by philwo** [comment]
I can do it! :) Is it OK to just go ahead or do you want to do any preparations?

**Comment by skeletonkey** [comment]
Thank you - I don't believe that there are any preparations that need to take place first.

I'm sure that we'll find out later :D

**Comment by skeletonkey** [comment]
Thank you @philwo !
