### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/rules_perl#48]
bzlmod requires stable download urls. This can only be achieved by generating a tarball from a tag or release on github otherwise the sha of the downloaded tarballs isn't guarenteed to be consistent over time.

**Comment by skeletonkey** [comment]
I should be able to get this done tomorrow.

**Comment by skeletonkey** [comment]
Created https://github.com/bazelbuild/rules_perl/releases/tag/0.1.0
